# Common application settings, used by all environments.
#
# These settings are read in `app/program.py` and can be overridden by
# environmental variables, thanks to `essentials-configuration` package.
# Refer to https://github.com/Neoteroi/essentials-configuration for more information.
#
# The ARM templates provided with the project template configure properly the application
# settings, so nothing more needs to be done here.
#

hsts: true

show_error_details: false

storage_account_name: "devasweeuwsa"

storage_account_key: "ueWYJeLdhDC1zEPRKF9IwYMqBPDoZSx+m+DsKSofP0+humqU4XEt6AvpWYF1HQxOKB3apQfLCPZGfVVyLVVXkw=="

db_connection_string: postgresql+asyncpg://postgres:postgres@localhost:5432/torino2

# Replace the following with an Application Insights' instrumentation key,
# to enable collection of telemetries. The same value can be configured using
# the environment variable APP_MONITORING_KEY
monitoring_key: ""

auth:
  audience: "" # api://e9ee7140-519d-458c-9621-0b3e110ea5a3
  issuer: "" # https://sts.windows.net/b62b317a-19c2-40c0-8650-2d9672324ac4/
