"""structure

Revision ID: 0f1fee7df457
Revises: 
Create Date: 2021-11-28 11:32:37.111746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f1fee7df457"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=2), nullable=True),
        sa.Column("english_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=8), nullable=True),
        sa.Column("two_letters_iso_code", sa.String(length=2), nullable=True),
        sa.Column(
            "three_letters_iso_code", sa.String(length=3), nullable=True
        ),
        sa.Column("english_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("language")
    op.drop_table("country")
    # ### end Alembic commands ###
